version: '3'
services:
  barlin:
    restart: always
    build: .
    ports:
      - 3080:3080
      - 3443:3443
    depends_on:
      - barlin-db
  barlin-db:
    image: mongo:4.4.18
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
